### ISSUE TITLE
Error 429 and 91

### ISSUE THREAD

**Issue by Nicals** [Nicals/aurora_linux#1]
[here on reddit](https://www.reddit.com/r/aurora/comments/6xnklc/aurora_installer_for_linux/dmhbrm8/)

Hey, thanks for this, it looks great. I just tried to use it to install Aurora on my fresh install of Kubuntu 17.04. Installed the 4 dependencies first. I get a single popup:

```
Error 429 was generated by Aurora
```

Then a ton of popups with:

```
Error 91 was generated by Aurora
```

Wine says:

```
lordcirth@lordcirth-K17:/SSD_data/Aurora4X/aurora_linux$ ./aurora.sh start
err:ole:CoGetClassObject class {6fba474b-43ac-11ce-9a0e-00aa0062bb4c} not registered
err:ole:CoGetClassObject class {6fba474b-43ac-11ce-9a0e-00aa0062bb4c} not registered
err:ole:CoGetClassObject no class object {6fba474b-43ac-11ce-9a0e-00aa0062bb4c} could be created for context 0x3
err:ole:CoGetClassObject class {00000100-0000-0010-8000-00aa006d2ea4} not registered
err:ole:create_server class {00000100-0000-0010-8000-00aa006d2ea4} not registered
err:ole:CoGetClassObject no class object {00000100-0000-0010-8000-00aa006d2ea4} could be created for context 0x5
```

EDIT: I switched wine-stable (1.8.7) to wine-development (2.0) and no difference.

EDIT2: Found this: https://www.reddit.com/r/aurora/comments/3zrdfg/playing_aurora_on_linux_with_wine_problem/ But LC_ALL="C" didn't help.

**Comment by lordcirth** [comment]
So I ran the install again, and noticed something in the output:

`Executing cd /home/lordcirth/.cache/winetricks/mdac27
Downloading http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe to /home/l
ordcirth/.cache/winetricks/mdac27
--2017-09-03 12:03:00--  http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.e
xe
Resolving download.microsoft.com (download.microsoft.com)... 23.34.218.252
Connecting to download.microsoft.com (download.microsoft.com)|23.34.218.252|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-03 12:03:01 ERROR 404: Not Found.

Executing cd /home/lordcirth/.cache/winetricks/mdac27
Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa
0d76/mdac_typ.exe to /home/lordcirth/.cache/winetricks/mdac27
--2017-09-03 12:03:02--  https://web.archive.org/web/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-
9a8c-42b2b4fa0d76/mdac_typ.exe
Resolving web.archive.org (web.archive.org)... 207.241.225.186
Connecting to web.archive.org (web.archive.org)|207.241.225.186|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://web.archive.org/web/20170101154733/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-
9a8c-42b2b4fa0d76/mdac_typ.exe [following]
--2017-09-03 12:03:02--  https://web.archive.org/web/20170101154733/http://download.microsoft.com/download/3/b/f/3bf7
4b01-16ba-472d-9a8c-42b2b4fa0d76/mdac_typ.exe
Reusing existing connection to web.archive.org:443.
HTTP request sent, awaiting response... 404 Not Found
2017-09-03 12:03:03 ERROR 404: Not Found.

------------------------------------------------------
Downloading https://web.archive.org/web/http://download.microsoft.com/download/3/b/f/3bf74b01-16ba-472d-9a8c-42b2b4fa
0d76/mdac_typ.exe failed
------------------------------------------------------
regsvr32: Failed to load DLL 'msjet40.dll'
Using winetricks 20170101 - sha1sum: c844fda0cca25ac9ed0ed1b55cd138cab6a4af16 with wine-2.0 (Ubuntu 2.0-3ubuntu1) and
 WINEARCH=win32
Executing w_do_call mdac28
Executing load_mdac28
Using native,builtin override for following DLLs: odbc32 odbccp32 oledb32
Executing winetricks_early_wine regedit C:\windows\Temp\_mdac28\override-dll.reg
Setting Windows version to nt40
Executing winetricks_early_wine regedit C:\windows\Temp\_mdac28\set-winver.reg
Executing cd /home/lordcirth/.cache/winetricks/mdac28
Executing wine mdac_typ.exe
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
err:richedit:ReadStyleSheet skipping optional destination
`

Seems I can't get 'msjet40.dll'.

**Comment by Nicals** [comment]
This is strange... When performing the installation on my side, I don't see any download from archive.org... Which version (commit) did this ?

Since 0b6bb052, the latest winetricks is used instead of the system one. Perhaps you had an hold winetricks with out of date links ?

**Comment by lordcirth** [comment]
Good idea.  I had winetricks 20170101 installed from Ubuntu 17.04 repos.  I've just downloaded the latest git winetricks (20170823-next), and it's downloading it.  It launches Aurora now!  Though the 'New' button is grayed out - probably an Aurora thing I'm forgetting?

Perhaps your script should check for a winetricks > 20170800 or something.

**Comment by Nicals** [comment]
Get the latest version of the script. It will download the current winetrick and fix this disabled new button.

Thanks for the feedback.
