### ISSUE TITLE
Installer breaks on directories with spaces

### ISSUE THREAD

**Issue by cobbleking** [Nicals/aurora_linux#10]
When I try to run ./aurora.sh install inside a directory with spaces in it, this is the resulting output:

./aurora.sh: line 83: [: /home/wren/non-managed: binary operator expected
./aurora.sh: line 97: [: /home/wren/non-managed: binary operator expected
mkdir: cannot create directory ‘/home/wren/non-managed’: File exists
mkdir: cannot create directory ‘software/aurora_linux-master/dl’: No such file or directory
Something went wrong. Aurora is not installed.

Of course, the workaround is rather simple, I just have to run it from somewhere else, but it's mildly annoying regardless.

**Comment by Nicals** [comment]
The workaround was a bunch of quotes. Thanks for the report. It should now be fixed.
