### ISSUE TITLE
DPI setting

### ISSUE THREAD

**Issue by Myvar** [Nicals/aurora_linux#9]
I use a 4K screen, so i had to mod the script to change the dpi so i could actually read the text in the installers, it would be nice to add a option for this or to set it automatically,

**Comment by Nicals** [comment]
Can you provide some details on how you modded the script to fix this issue ?

**Comment by Myvar** [comment]
I just lunched wine cfg in the prefex before the installer started and changed the dpi setting in the desktop integration tab
